[tool.pytest.ini_options]
addopts = [
    "-vv",
    "--cov=application/",
    "--cov-report=term",
    "--cov-fail-under=85",
]
pythonpath = "."


[tool.mypy]
files = ["application/*.py"]
strict = true
ignore_missing_imports = true


[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade,
    "N",  # pep8-naming
    "A",  # flake8-builtins
]
preview = true